Disable call to _write_project_config in b2 recipe
- It looks like AIX and Sparc CI were able to find the _write_project_config
  method after it was added back in. However, b2 still fails to build on Sparc
  and AIX because it was not able to find the project jam file. The following error
  was occurring:
    cxx.jam (No such file or directory)
    ERROR: rule "cxx.init" unknown in module "toolset".

- Let's try disabling the call to _write_project_config() to see if it's causing the
  b2 build issue on Sparc and AIX.